name: Publish GitHub NPM Example

on:
  push:
    branches:
      - main
    paths:
      - tsconfig-project/**
  workflow_dispatch:
    
jobs: 
  npm-publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tsconfig-project

    steps:
      - uses: actions/checkout@v4

      #Setup Nodejs
      - name: Setup Node.js 16 
        uses: actions/setup-node@v4
        with: 
          node-version: "16.x"

      - run: git config user.email "vidaa@vestas.com"
      - run: git config user.name "VIDAA"  
      - run: yarn version --patch --message "Bump version to %s"

      - run: git push 
      - run: git push --follow-tags

      - name: publish to github
        run: 
          npm config set registry https://npm.pkg.github.com
          npm set //npm.pkg.github.com/:_authToken ${{ env.NODE_AUTH_TOKEN }}
          npm run publish:github
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN}}